// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSH1KuFHusybhyU_bVhc6L2Jc4m-SxoWA',
    appId: '1:1046831940536:web:795629fbba2ea66eae054d',
    messagingSenderId: '1046831940536',
    projectId: 'street-report-52b23',
    authDomain: 'street-report-52b23.firebaseapp.com',
    databaseURL: 'https://street-report-52b23-default-rtdb.firebaseio.com',
    storageBucket: 'street-report-52b23.appspot.com',
    measurementId: 'G-TYJC9K7YH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoptRPCm5nnkh4uwtEtAPbE-BOViZH7eg',
    appId: '1:1046831940536:android:7cec97873caf521cae054d',
    messagingSenderId: '1046831940536',
    projectId: 'street-report-52b23',
    databaseURL: 'https://street-report-52b23-default-rtdb.firebaseio.com',
    storageBucket: 'street-report-52b23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ4OkomrulEaBPkqeVVRTKO1qGkYfbVzc',
    appId: '1:1046831940536:ios:bebf2b7232cecd50ae054d',
    messagingSenderId: '1046831940536',
    projectId: 'street-report-52b23',
    databaseURL: 'https://street-report-52b23-default-rtdb.firebaseio.com',
    storageBucket: 'street-report-52b23.appspot.com',
    iosClientId: '1046831940536-c4hhba0595eg1hqqh2mdvgv60isuvkr4.apps.googleusercontent.com',
    iosBundleId: 'com.example.streetReport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ4OkomrulEaBPkqeVVRTKO1qGkYfbVzc',
    appId: '1:1046831940536:ios:bebf2b7232cecd50ae054d',
    messagingSenderId: '1046831940536',
    projectId: 'street-report-52b23',
    databaseURL: 'https://street-report-52b23-default-rtdb.firebaseio.com',
    storageBucket: 'street-report-52b23.appspot.com',
    iosClientId: '1046831940536-c4hhba0595eg1hqqh2mdvgv60isuvkr4.apps.googleusercontent.com',
    iosBundleId: 'com.example.streetReport',
  );
}
